# Examples Lecture 6: Lists


### Lists
In the examples below, we will use `lists`. They are a topic we will discuss in detail soon, but to have a enough information to follow along the examples, let us briefly describing them before going into `for` loops.

`Lists`` might be the most flexible collection object in Python. \
They are ordered collections which you can fill them with different types of objects (strings, numbers, other lists, etc.). \
You can iterate over them, add + remove elements etc. \
To make a list you surrond the elements with square brackets and separate items by commas

In [8]:
aList = [1.2, -6.5, 8.0, -3.4, 7.9]
names = ['Diana', 'Bruce', 'Clark']
randomStuff = [123, 'ICT', True]
emptyList = []


In [9]:
#Use the unique index — starting from 0
names = ['Diana', 'Bruce', 'Clark']
names[0]       # has the value ‘Diana’
names[1]       # has the value ‘Bruce’
names[2]       # has the value ‘Clark’

'Clark'

In [12]:
names = ['Diana', 'Bruce', 'Clark']
print('original list',names)
names[1] = 'Peter'
print('list has change to ',names)

original list ['Diana', 'Bruce', 'Clark']
list has change to  ['Diana', 'Peter', 'Clark']


In [23]:
for name in names:
    print(name)

Diana
Bruce
Clark


In [24]:
for i in range(0,len(names)):
    print(names[i])

Diana
Bruce
Clark


In [15]:
help(names)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [21]:
names = ['Diana', 'Bruce', 'Clark']
print(names,' three names makes the length ',len(names))
emptyList = []
print(emptyList,' an empty list has',len(emptyList),' elements')


['Diana', 'Bruce', 'Clark']  three names makes the length  3
[]  an empty list has 0  elements


In [26]:
print(names)
names.append('Arthur')
print(names)
names.pop()
print(names)
names.insert(1,'Peter')
print(names)

['Diana', 'Bruce', 'Clark']
['Diana', 'Bruce', 'Clark', 'Arthur']
['Diana', 'Bruce', 'Clark']
['Diana', 'Peter', 'Bruce', 'Clark']


In [27]:
bool = 'Peter' in names
print(bool)

True


In [28]:
if 'Peter' in names:
    print('Peter is in the list')
    print('and is in the index',names.index('Peter'))

Peter is in the list
and is in the index 1


In [30]:
names.index('Mafalda')

ValueError: 'Mafalda' is not in list

### remove by using the "remove" method (access by element)

In [32]:
# We can remove an element from a list by using the remove method
# If the element is not in the list, a ValueError is raised
x = [2, 4, 6, 4, 2, 4] 
print('original list',x)
x.remove(4)     
print('list has changed to ',x)
x.remove(3)     # Value Error


original list [2, 4, 6, 4, 2, 4]
list has change to  [2, 6, 4, 2, 4]


ValueError: list.remove(x): x not in list

### remove by using the pop method (access by index)

In [33]:
x = [2, 4, 6, 4, 2, 4] 
print('original list',x)
x.pop() 
print('list has changed to ',x)
y = x.pop(3)
print('list has changed to ',x)
print('the value removed is ',y)     


original list [2, 4, 6, 4, 2, 4]
list has changed to  [2, 4, 6, 4, 2]
list has changed to  [2, 4, 6, 2]
the value removed is  4


### using del (delete)

In [34]:
x = [2, 4, 6, 4, 2, 4] 
print('original list',x)
del(x[1]) 
print('list has changed to ',x)    

original list [2, 4, 6, 4, 2, 4]
list has changed to  [2, 6, 4, 2, 4]


In [35]:
x = [2, 4, 6, 4, 2, 4] 
print('original list',x)
x.clear() 
print('list has changed to ',x)   

original list [2, 4, 6, 4, 2, 4]
list has changed to  []


### Sorting elements (the "sorted()" function)

In [37]:
x = [2, 4, 6, 4, 2, 4]
print('original list',x) 
y = sorted(x)     # y will be sorted; x remains unchanged
print('the y list has been created',y)
print('the original list',x,' remains unchanged')
z = sorted(x, reverse = True)    # z will be sorted in reverse order 
print('the z list has been created',z)

original list [2, 4, 6, 4, 2, 4]
the y list has been created [2, 2, 4, 4, 4, 6]
the original list [2, 4, 6, 4, 2, 4]  remains unchanged
the z list has been created [6, 4, 4, 4, 2, 2]


### Sorting elements (the "alist.sort()" method)

In [39]:
x = [2, 4, 6, 4, 2, 4]
print('original list',x) 
x.sort()     # x will be sorted in place
print('the x list has been changed',x)
x.sort(reverse = True)    # x will be sorted in reverse order 
print('the x list has been changed',x)

original list [2, 4, 6, 4, 2, 4]
the x list has been changed [2, 2, 4, 4, 4, 6]
the x list has been changed [6, 4, 4, 4, 2, 2]


### Concatenation
Operator "+" is overloaded such that when acts on lists\
it puts one after the other ("concatenation")


In [43]:
x = [2, 4, 6]
names = ['Diana', 'Bruce', 'Clark']
y = x + names 
print(y)


[2, 4, 6, 'Diana', 'Bruce', 'Clark']


Notice this may not be what you expect when the lists\
contain numbers, but that is how it works.

In [44]:
x = [2, 4, 6]
y = [1, 3, 5]
z = x + y
print(z)
w = x * 3
print(w)

[2, 4, 6, 1, 3, 5]
[2, 4, 6, 2, 4, 6, 2, 4, 6]


### Slicing (access portions of a list)

In [48]:
x = [1,2,3,4,5,6,7,8,9,10]
print('original list',x)
print(x[1:3])	# taking index 1 to 3, not including 3
print(x[:4])	# taking index 0 to 4, not including 4
print(x[6:])	# taking index 6 to the end
print(x[:9:2])  # taking index 0 to 9, with a step of 2
print('the original list',x,' remains unchanged')	

original list [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 3]
[1, 2, 3, 4]
[7, 8, 9, 10]
[1, 3, 5, 7, 9]
the original list [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  remains unchanged


### List of lists (Multidimensional Lists)
We can create list of lists

In [56]:
myList = []
myList.append([1, 2, 3])
myList.append(['a', 'b', 'c']) 
myList     


[[1, 2, 3], ['a', 'b', 'c']]

In [54]:
# create a multidimensional list with 3 rows and 4 columns
x = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
print(x)
print(x[0])
print(x[1])
print(x[2])
print(x[0][0])
print(x[0][1])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
1
2


In [55]:
# create the same list using numpy
import numpy as numpy
x = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x)
print(x[0])
print(x[1])
print(x[2])
print(x[0][0])
print(x[0][1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
1
2


In [52]:
def printboard(n,m):
    '''Generate a random board for Boggle
	4x4 board
	Store the board in a 2D list
	Each space on the board contains one randomly selected letter
	Display the board; sample board:
    '''
    import random
    board = []
    for i in range(n):
        row = []
        for j in range(m):
            row.append(chr(random.randint(65, 90)))
        board.append(row)
    for row in board:
        print(row)

printboard(4,6)

['W', 'O', 'U', 'U', 'T', 'X']
['G', 'P', 'N', 'B', 'M', 'V']
['F', 'G', 'R', 'P', 'L', 'Y']
['J', 'A', 'L', 'J', 'U', 'F']


### Tuples
They also permit to pack arbitrary objects, but with some differences:
- length cannot be changed
- Items cannot be assigned individually


In [57]:
t1=() # empty tuple
t2=(15,) # tuple length one 
t3=("abc", 6) #tuple length two
aTuple = (1,"ICT",3.14) # tuple with three different elements 


In [59]:
print(aTuple)
aTuple[1] = "Python" # TypeError: 'tuple' object does not support item assignment

(1, 'ICT', 3.14)


TypeError: 'tuple' object does not support item assignment

In [1]:
L=[1,'two',3.0]
L

[1, 'two', 3.0]

You can use the same indexing syntax

In [2]:
print(L[0:3])
print(L[1])

[1, 'two', 3.0]
two


You can also `.append` to them, `.pop` items off the end, etc. Create a list and hit <TAB> twice to get some ideas

In [3]:
L.append('3')
print(L)


[1, 'two', 3.0, '3']


In [4]:
L.pop()
L

[1, 'two', 3.0]